### ISSUE TITLE
Small spitters don't drop loot

### ISSUE THREAD

**Issue by path9263** [cppmonkey/FactorioAlienLoot#1]
I believe there is a typo in your code, you have "small-biter" twice but no "small-spitter".  Lines 11 and 12:

```
AddLootToEntity("unit","small-biter","alien-artifact",.1,1,1)
AddLootToEntity("unit","small-biter","alien-artifact",.1,1,1)
```

**Comment by cppmonkey** [comment]
Thanks for the heads up. Just making the changes to the code and resubmitting to the mod site
